# Generated by Django 5.1.5 on 2026-08-25 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('started', 'Application started'), ('applied', 'Marked as applied'), ('recruiter_screen', 'Recruiter screen'), ('technical', 'Technical'), ('manager', 'Manager'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, help_text='Set only when the candidate confirms they applied.', null=True)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('overall', models.PositiveSmallIntegerField()),
                ('resume_score', models.PositiveSmallIntegerField()),
                ('targeting_score', models.PositiveSmallIntegerField()),
                ('ats_score', models.PositiveSmallIntegerField()),
                ('interview_score', models.PositiveSmallIntegerField()),
                ('method', models.CharField(choices=[('self_report_v1', 'Self-reported answers, v1 rules')], default='self_report_v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('target_role', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(blank=True, choices=[('0-2', '0–2 years'), ('3-5', '3–5 years'), ('6-10', '6–10 years'), ('10+', '10+ years')], max_length=8)),
                ('work_status_pref', models.CharField(blank=True, choices=[('f1', 'F-1'), ('opt', 'OPT'), ('stem-opt', 'STEM OPT'), ('h1b', 'H-1B'), ('gc', 'Green Card'), ('citizen', 'US Citizen'), ('other', 'Other')], max_length=16)),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('any', 'Open to all')], max_length=8)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('linkedin_url', models.URLField(blank=True)),
                ('lead_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=400, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('parse_status', models.CharField(choices=[('pending', 'Awaiting parse'), ('parsed', 'Parsed'), ('failed', 'Parse failed'), ('skipped', 'Not parsed')], default='pending', max_length=12)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('extracted_value', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('confirmed_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
