# Generated by Django 5.1.5 on 2026-08-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='candidates__created_d94c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['target_role'], name='candidates__target__631a1e_idx'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='resumeextraction',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='candidates.resume'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_application_per_candidate'),
        ),
        migrations.AddConstraint(
            model_name='resumeextraction',
            constraint=models.UniqueConstraint(fields=('resume', 'field'), name='unique_extraction_per_field'),
        ),
        migrations.AddConstraint(
            model_name='savedjob',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_saved_job_per_candidate'),
        ),
    ]
