# Generated by Django 5.1.5 on 2026-08-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='upload_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Awaiting upload'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed'), ('deleted', 'Deleted')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Awaiting parse'), ('parsed', 'Parsed'), ('failed', 'Parse failed'), ('skipped', 'Not parsed')], default='skipped', max_length=12),
        ),
        migrations.AlterField(
            model_name='resume',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CandidateAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
