# Generated by Django 5.1.5 on 2026-08-25 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], max_length=16)),
                ('board_token', models.CharField(help_text="The employer's board slug, e.g. the 'stripe' in boards-api.greenhouse.io/v1/boards/stripe/jobs", max_length=120)),
                ('employer_name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('last_ingest_status', models.CharField(blank=True, max_length=200)),
                ('last_job_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['employer_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'board_token'), name='unique_board_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], max_length=16)),
                ('source_job_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('employment_type', models.CharField(blank=True, max_length=40)),
                ('role_family', models.CharField(choices=[('software', 'Software Engineer'), ('devops', 'DevOps Engineer'), ('cloud', 'Cloud Engineer'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('salesforce', 'Salesforce Developer'), ('qa', 'QA Engineer'), ('security', 'Cybersecurity Engineer'), ('business_analyst', 'Business Analyst'), ('product', 'Product Manager'), ('other_it', 'Other IT'), ('non_it', 'Not IT'), ('unknown', 'Unclassified')], default='unknown', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry'), ('mid', 'Mid'), ('senior', 'Senior'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('sponsorship_status', models.CharField(choices=[('explicit_offered', 'Posting states sponsorship is available'), ('explicit_not_offered', 'Posting states sponsorship is not available'), ('not_stated', 'Posting does not say')], default='not_stated', help_text='Set from explicit wording in the posting only. Never inferred.', max_length=24)),
                ('sponsorship_evidence', models.TextField(blank=True, help_text='The sentence the status was read from, so any claim is auditable.')),
                ('application_url', models.URLField(max_length=600)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.employersource')),
            ],
            options={
                'ordering': ['-posted_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('experience_match', models.BooleanField(default=False)),
                ('location_match', models.BooleanField(default=False)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['role_family', '-posted_at'], name='jobs_job_role_fa_d6b051_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-last_seen_at'], name='jobs_job_is_acti_e7d0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['sponsorship_status'], name='jobs_job_sponsor_aad1a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'source_job_id'), name='unique_job_per_source'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['candidate', '-score'], name='jobs_jobmat_candida_0f7ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobmatch',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_match_per_candidate_job'),
        ),
    ]
