# Generated by Django 5.1.5 on 2026-08-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('work_authorization', models.CharField(choices=[('f1', 'F1 student'), ('opt', 'Post-completion OPT'), ('stem-opt', 'STEM OPT extension'), ('h1b', 'H-1B'), ('gc', 'Green card holder'), ('citizen', 'US citizen'), ('other', 'Other / not sure')], default='other', max_length=16)),
                ('target_roles', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('call_booked', 'Demo call booked'), ('engaged', 'Engaged'), ('declined', 'Declined'), ('spam', 'Spam')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Internal only. Never shown to the candidate.')),
                ('source_path', models.CharField(blank=True, max_length=200)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='leads_lead_created_921505_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resume', 'Resume'), ('transcript', 'Transcript'), ('offer', 'Offer letter'), ('other', 'Other')], default='resume', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('external_url', models.URLField(blank=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('meeting_url', models.URLField(blank=True)),
                ('external_event_id', models.CharField(blank=True, help_text='Calendly event id, once wired.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='leads.lead')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
    ]
